# -*- coding: utf-8 -*-
"""trapezio

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm

- indicar que o programa calcula a integral pelo metodo dos trapezios da funcao f no intervalo (a,b)
- pedir para inserir o valor de k desejado
- printar que vai ser escolhido os intervalo que deseja calcular a integral  
- pedir pra inserir o valor inicial do intervalo (a)
- pedir pra inserir o valor final do intervalor (b)
- definir a função da area do trapézio trapezio(a,b,k)
-    calcular o delta (b-a)/2**k
-    fazer a lista vazia de fj
-    colocar o contador do j
-    realizar for j in range(1,2**k):  f = f(a+j*delta) j+=1 fj.append(f)
-    retornar o Tk com o somatorio dos valores da lista de fj
- printar que a integral de f(x) nos intervalos (a,b) calculada na ordem k é Tk
"""

import math as mt

print("esse programa deseja calcular a integral de sen(x) no intervalo [0,pi]")

k = int(input("Insira o valor de k desejado \n"))
a = 0
b = mt.pi

def trapezio(a,b,k):
  delta = (b - a)/2**k
  j = 1
  fj=[]
  for j in range(1,2**k):
    f = mt.sin(a + j*delta)
    j = j +1
    fj.append(f)
  T = delta/2 * (mt.sin(a) + 2*sum(fj) + mt.sin(b))
  return T

Tk = trapezio(a,b,k)

print("a integral de sen(x) nos intervalo [0,pi] calculada na ordem %.d é %.5f" %(k,Tk))