# -*- coding: utf-8 -*-
"""funcao2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NSaHpHs7uUCykuGoQH26_M_LzGf5GejG
"""

import matplotlib.pyplot as plt
import numpy as np

print("esse programa faz o gráfico da função f(x) = sin(0.1xˆ2 + 3) - sqrt(2/x) ")
def f(x):
  return np.sin(0.1*x**2 + 3) - np.sqrt(2/x)

x = np.linspace(2,10,200)
y = f(x)

plt.plot(x,y)
plt.xlabel('x',fontsize = 15)
plt.ylabel('f(x)',fontsize = 15)
plt.title("Função")
plt.grid(True)
plt.savefig("funcao2.pdf")
plt.show()