# -*- coding: utf-8 -*-
'''
- Sem erros.

OBS: Poderia ter feito uma breve introdução sobre do que se trata o programa
OBS: Poucos comentários.
OBS: Perda de generalidade ao forçar as notas a serem inteiras.
OBS: Variável "quadrado" não foi utilizada.
OBS: Tomar cuidado com os prints. Não fica claro o que quer dizer com "a média com o codigo" ou "o desvio com o codigo"
OBS: Escolher melhor os nomes das variáveis a serem utilizadas. Os nomes "eqm" e "eqs" não são
grandes indicativos da real finalididade das variáveis.
'''


"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

# -*- coding: utf-8 -*-
import numpy as np
from math import sqrt

imp = np.loadtxt ("media.txt") #importa o arquivo com a lista de notas dos alunos
n = np.array(imp,int) #transforma a lista imp em um array com numeros inteiros
quadrado = n**2 #lista com o quadrado de cada numero

mi = sum(n)/len(n) #media da turma calculada somando as notas e dividindo pelo número de alunos 
eqm = np.mean(n)

somatorio = 0
for i in n:
    somatorio += (i - mi)**2
desvio = sqrt(1/(len(n) - 1) * somatorio) #calcula o desvio padrão das notas
eqs = np.std(n)

aprovados = 0
reprovados = 0 
for x in n:
    if x >= 7:
        aprovados +=1
    elif x < 3:
       reprovados +=1

print("essa turma tem %d alunos, a média de notas é %.1f e o desvio padrão é %.1f." %(len(n), mi, desvio))
print("a média com o codigo é %.1f" %(eqm))
print("o desvio com o codigo é %.1f" %(eqs))

print("o número de alunos aprovados foi: %d" %(aprovados))
print("o número de alunos reprovados foi: %d" %(reprovados))
