'''
Gabriella
 - sem erros
'''
# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

# -*- coding: utf-8 -*-
import math as mt 

#esse código quer calcular o seno de um número a partir do somatório e comparar com mt.sin
x = 1.2 #valor do seno que será calculado

somatorio=0
for i in range(6):
  somatorio += (-1)**i / mt.factorial(2*i+1) * x**(2*i+1)

seno = somatorio

eq = mt.sin(x)

print("Utilizando o somatório temos que o seno de %.1f é %.10f" %(x, seno))
print("Utilizando mt.sin temos que seno de %.1f é %.4f" %(x,eq))
