'''
Sem erros.
'''

# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

# -*- coding: utf-8 -*-
print("esse programa mostra os divisores de um número")
n = int(input("Insira um número inteiro positivo: "))
y = n #contador que vai receber os valores para fazer a divisão
soma = 0 #contador para somar o número de vezes que o loop ocorrerá
while y!= 0:
  if n%y == 0: # o resto da divisão sendo zero, então é um divisor 
    print(y)
    soma+=1
  y -= 1  
  
print("Esses são os divisores do número %d, totalizando %d divisores " %(n,soma))
