# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

C = 32.5 #temperatuda em celsius
F = (C*9./5) + 32
print (F) # o nome desse arquivo deve ser Farenheit.py