# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

from math import *

R = 5 # raio do cilindro em cm
Ac = pi * R**2 # area do circulo
H = 20 # altura do cilindro em cm
C = 2 * pi * R # comprimento do circulo

V = Ac * H 
A = 2* Ac + C * H


print(V)