# -*- coding: utf-8 -*-
"""euler_tangente

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

import numpy as np
from math import *
import matplotlib.pyplot as plt

print("Esse programa utiliza o método de Euler para resolver a EDO x'(t)= xˆ2 + 1")

def dxdt(x,t):
  return x**2 + 1

ti = 0            # t inical
tf = 1            # t final
xi = 0            # x inicial
N = 5             # numero de pontos desejados
h = (tf - ti)/N   # passo
x = np.zeros(N+1) 
t = np.arange(ti,tf+h,h)
x[0] = xi
for k in range(len(t)-1):
  print(t[k],x[k],tan(t[k]))
  x[k+1] = x[k] + h*dxdt(x[k],t[k])

plt.plot(t,x)
plt.plot(t,np.tan(t))
plt.show()