'''
O programa não roda.
Erro: A aluna não importou a biblioteca matplotlib.pyplot. (linha 15)
3/4
'''

# -*- coding: utf-8 -*-
"""histograma

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""
import matplotlib.pyplot as plt
import numpy as np 
import math as mt
print('esse programa faz o histograma de dados de um experiemento da gravidade, calculando a media e o desvio padrão dos valores encontrados')
x = np.loadtxt("gravidade.dat")

#comandos para fazer o histograma
plt.hist(x ,bins = 20,ec = "k", label="20 bins") #ec é para o edgecolor (cor da linha da borda) e o k para black 
plt.hist(x ,bins = 60,ec = "k", label="60 bins")
plt.xlabel('gravidade [cm/sˆ2]')
plt.ylabel('quantidade de medidas')
plt.title('Histograma dos valores da gravidade do experimento')
plt.legend()
plt.show()

#media das acelerações
media = sum(x)/len(x)
media2 = np.mean(x)

#cálculo o desvio padrão das velocidades
somatorio = 0
for i in x:
    somatorio += (i - media)**2
desvio = mt.sqrt(1/(len(x) - 1) * somatorio) 
desvio2 = np.std(x)

print('a média de acelerações encontradas: %.6f' %(media))
print('a média usando np.mean: %.6f' %(media2))
print('o desvio padrão das acelerações: %.6f' %(desvio))
print('o desvio usando np.std: %.6f' %(desvio2))
