'''
Não printa o valor do seno 'exato'
[linha 39]- O erro esperado está calculado errado
[linha 36]- Mal nome de variável, 'prox_termo' não é o próximo termo da série, mas a série em um termo a mais;
'valor_esperado' é o próximo termo da série.
4.5/6
'''
# -*- coding: utf-8 -*-
"""seno

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

# -*- coding: utf-8 -*-
import math as mt
import matplotlib.pyplot as plt
import numpy as np

print("esse programa deseja calcular a serie de Taylor da função sen(x)")

def taylor_seno(x,n):  #função que calcula o seno atraves da serie de Taylor
  seno = 0
  for i in range(n):
    seno += (-1)**i / mt.factorial(2*i+1) * x**(2*i+1)  #soma todos as partes da serie de taylor
  return seno


#letra c
print("- 1c) variamos o valor de x, mas truncamos o valor do termo em 4")
nc = 4
xc = 0
for xc in range(1,6):
  sen_c = taylor_seno(xc,nc)
  x0 = 0
  prox_termo = taylor_seno(xc+1,nc)
  valor_esp = (xc - x0)**(nc+1)/mt.factorial(nc+1)
  print("o seno de %.2f" %(xc))
  print("ordem:%.d , serie: %.5f , proximo termo será: %.5f , valor esperado: %.5f" %(nc,sen_c,prox_termo, valor_esp))

#letra d
print("\n- 1d) Gráfico que mostra como o seno varia a medida que n e x variam")
xd = np.linspace(0,3*np.pi/2,51)
y = np.sin(xd)
y2 = taylor_seno(xd,2)
y3 = taylor_seno(xd,3)
y4 = taylor_seno(xd,4)
y5 = taylor_seno(xd,5)

x_graus = np.degrees(xd)  #converte os valores do eixo x de radianos para graus
plt.plot(x_graus,y,label='sen(x)')
plt.plot(x_graus,y2, label='n=2')
plt.plot(x_graus,y3,label='n=3')
plt.plot(x_graus,y4,label='n=4')
plt.plot(x_graus,y5,label='n=5')
plt.grid(True)
plt.ylim(-2,2)  #limita a variação do eixo y
plt.title("Serie de Taylor - sen(x)")
plt.xlabel('x (graus)')
plt.ylabel('sen(x)')
plt.legend()
plt.show()
