'''
 - Sem erros
OBS: é salvo e plotado um ponto a mais do que o desejado, mas o método
é aplicado corretamente.
'''
# -*- coding: utf-8 -*-
"""euler_tangente

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T3lw8427H0f5JtRCGofFNI85S97xrPfP
"""

import numpy as np
from math import *
import matplotlib.pyplot as plt

print("Esse programa utiliza o método de Euler para resolver a EDO x'(t)= xˆ2 + 1")

def derivada(x,t):
    return x**2 +1

def Euler(ti,tf,xi,N,dxdt):
  h = (tf - ti)/N   # passo
  x = np.zeros(N+1) 
  t = np.arange(ti,tf+h,h)
  x[0] = xi
  print("t", "  x", "  tangente")
  for k in range(len(t)-1):
    print(t[k],x[k],np.tan(t[k]))
    x[k+1] = x[k] + h*dxdt(x[k],t[k])   # próximo valor de x 
  return x,t

ti = 0            # t inical
tf = 1            # t final
xi = 0            # x inicial
N = 5             # numero de pontos desejados
x,t = Euler(ti,tf,xi,N,derivada) # a função Euler com esses valores dará o valor de x e t 

#plotando o gráfico
plt.plot(t,x,label="Euler")
plt.plot(t,np.tan(t),label ="tangente")
plt.xlabel("tempo")
plt.ylabel("posição")
plt.legend()
plt.show()
