# -*- coding: utf-8 -*-
"""mysum

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

def mysum(x):
  """ 
  Calcula a soma dos itens de uma lista 
  return a soma dos valores da lista
  """

  soma = type(x[0])()        # o contador terá valor nulo e estará assumindo o tipo dos elementos da lista 
  for i in x:                # para i dentro da lista x avaliada na função
    soma += i                # somará cada valor que o i assumir
  return soma 

lista1 = [1,2,3]             # define a lista 1
lista2 = ["Hello ","World!"] # define a lista 2
lista3 = [[1,2],[3,4]]       # define a lista 3
S1 = mysum(lista1)           # variavel que assumirá o valor da soma dos valores da lista 1
S2 = mysum(lista2)           # variavel que assumirá o valor da soma dos valores da lista 2
S3 = mysum(lista3)           # variavel que assumirá o valor da soma dos valores da lista 3

print(S1)
print(S2)
print(S3)