'''
 - Sem erros.

OBS: Eixos sem rótulo
'''

# -*- coding: utf-8 -*-
"""funcao1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

import matplotlib.pyplot as plt
import numpy as np

print("esse programa faz o gráfico da função f(x) = eˆ(-x) - sin(x*pi/2) ")
def f(x):
  return np.exp(-x) - np.sin(np.pi*x/2)

x = np.linspace(0,4,200)
y = f(x)

plt.plot(x,y)
plt.title("Função")
plt.grid(True)
plt.savefig("funcao1.pdf")
plt.show()