'''
sem erros
'''

# -*- coding: utf-8 -*-
"""mysum

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""
# -*- coding: utf-8 -*-

#Este programa quer obter a soma dos elementos de listas

def mysum(x):
  """
  Calcula a soma dos itens de uma lista
  return a soma dos valores da lista
  """

  soma = type(x[0])()        # o contador terá valor nulo e estará assumindo o tipo dos elementos da lista
  for i in x:                # i irá percorrer os valores de da lista x
    soma += i
  return soma

lista1 = [1,2,3]
lista2 = ["Hello ","World!"]
lista3 = [[1,2],[3,4]]
S1 = mysum(lista1)           # variavel que assumirá o valor da soma dos valores da lista 1
S2 = mysum(lista2)           # variavel que assumirá o valor da soma dos valores da lista 2
S3 = mysum(lista3)           # variavel que assumirá o valor da soma dos valores da lista 3

print(S1)
print(S2)
print(S3)
