# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

C = -20 
while (C<40):
  F = (C*9./5) + 32
  C = C + 5
  print("%.2f °C = %.2f °F" %(C,F))