# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

numero = int(input("Quer saber o fatorial de que numero? \n"))

resultado=1
contador=1

while contador <= numero:
    resultado *= count      #começa no 1 e multiplica por 2,3,... ate chegar ao numero desejado, gerando o fatorial
    contador += 1

print(resultado)
