# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

numero = int(input("Quer saber o fatorial de que numero? \n"))

resultado=1
count=1

while count <= numero:
    resultado *= count
    count += 1

print(resultado)