# -*- coding: utf-8 -*-
"""salvando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDuEoIEzi7dgC4MwNdrgYJa1xh2ssrXm
"""

n = int(input("Numero positivo: ")) 
impar = n - 1
menor = impar - 2
maior = impar + 2
soma = maior + menor + impar
print(menor, impar, maior) 
print(soma)